name: bot-lebaran
services:
  bot-lebaran:
    public: true
    image: okteto.dev/bot-lebaran:latest
    build: .
    replicas: 1
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    # ports:
    #   - 80
    # resources:
    #   cpu: 100m
    #   memory: 128Mi