const { TAHUN_HIJRIAH } = require('../config/keys')
const kumpulanUcapan = [
    "Ada Jaka meminta izin, ingin meminang anak Bu Titin. Minal aidzin wal faidzin, mohon maaf lahir dan batin.",
    "Anak kucing baru lahir, diajarin emak bahasa latin. Ramadan suci berakhir, mohon maaf lahir batin.",
    "Barang antik jangan diabaikan, dijaga dengan baik oleh pak Udin. Saya cantik mohon dimaafkan, maaf tulus lahir dan batin",
    "Berharap pada lesung, yang ada hanya rumpun jerami. Ingin hati bertemu langsung, namun yang sampai hanya pesan ini. Minal aidzin wal faidzin, mohon maaf lahir dan batin.",
    "Biar kenyang makan kentang, makan kentang dipinggir kolam ikan. Hari yang fitri sudah datang, segala salah mohon dimaafkan.",
    "Bila semua salah orang kita timbun, sampah pergaulan akan bebani diri. Bila lebaran kita saling memberi ampun, semoga dosa kita tak lagi saling membebani. Selamat hari raya Idul Fitri " + TAHUN_HIJRIAH + " H",
    "Bingkai ketupat daun kelapa, kelapa muda enak terasa. Satu Syawal hampir tiba, mohon maaf atas salah dan dosa.",
    "Coba lihat ke luar dan lihat, matahari tersenyum, pohon-pohon menari, dan burung-burung berkicau untukmu. Semua itu merupakan rasa syukur makhluk ciptaan-Nya di hari yang fitri ini, mohon maaf lahir dan batin.",
    "Covid-19 butuh diwaspadai, jagalah diri dengan vaksinasi. Hari lebaran terasa nyaman di hati, apabila kau katakan tidak lagi sakit hati.",
    "Dalam khilafku, dalam salahku, dalam budiku yang pernah melukaimu, beserta segala kata-kata yang tak menyenangkan hatimu, di hari yang suci ini maafkanlah aku.",
    "Dari semua berkah yang aku syukuri, tak peduli apakah itu besar atau kecil, persahabatan kita adalah hal yang paling kusyukuri. Semoga Allah selalu memberimu berkah dengan segala hal yang layak kamu dapatkan. Selamat Idul Fitri " + TAHUN_HIJRIAH + " H",
    "Di khilafku, dalam salahku, dalam budiku yang pernah melukaimu, dan semua kata-kataku yang terucap tak menyenangkan hatimu, di hari yang indah nan suci ini maafkanlah aku.",
    "Dulu kita sahabat, berteman bagai ulat. Tapi tak sempat jadi kupu-kupu, karena kamu menusuk dari belakang. Tapi, semua sudah lewat, anggap saja masa lalu. Mari saling memaafkan di hari kemenangan.",
    "Hanya maafmu kawan yang akan menjadi pelengkap di hari yang fitrah ini. Mohon maaf lahir dan batin.",
    "Hari Raya makan ketupat, ketupat di potong menjadi empat. Walau untuk bertemu kita tak sempat, namun ucapan maaf ku kirim cepat. Maaf lahir dan batin.",
    "Makan sahur lauknya ikan. Sesaat lagi kita Lebaran, semoga semua salah dan khilaf dimaafkan.",
    "Masih ada salah yang tersirat, terucap, dan terlakukan. Di hari yang penuh kesucian ini, mohonlah dimaafkan. Karena sesungguhnya tiada manusia yang tak luput dari salah dan tiada manusia yang sempurna.",
    "Ikan bakar ikan dori, enak dibakar tanpa micin. Kami ucapkan selamat hari raya Idul Fitri " + TAHUN_HIJRIAH + " H, mohon maaf lahir dan batin.",
    "Ini lebih dari sekedar ucapan selamat Idul Fitri " + TAHUN_HIJRIAH + " H. Pesan ini dibuat dengan hangat dan penuh kasih sayang. Karena ini hanya untukmu.",
    "Izin ke Jogja pamit kuliah, ternyata ke Bandung membeli liontin. Jika selama ini banyak yang salah, mohon maafkan lahir dan batin.",
    "Jajar genjang belah ketupat, lebaran makan ketupat. Logaritma trigonometri, Selamat Hari Raya Idul Fitri " + TAHUN_HIJRIAH + " H.",
    "Jam sudah bersuara ding dong, kalau diriku banyak salah tolong dimaafin dong.",
    "Jika jiwa sebening air, jangan sampai mengeruh. Jika hati seputih awan, jangan sampai menjadi mendung. Raih kemenangan bersama dengan saling memaafkan. Selamat hari raya Idul Fitri " + TAHUN_HIJRIAH + " H, mohon maaf lahir dan batin.",
    "Jika tangan tak saling menjabat, THR dapat melekatkan silaturahmi, sobat.",
    "Keluarga cemara pergi liburan, Pergi liburan ke Surabaya. Mohon maaf atas kesalahan, Agar menjadi fitri di hari raya",
    "Ketupat dibelah rata, kita makan bersama-sama. Aduh esok lebaran tiba, mohon maaf segala salah dan sangka.",
    "Ketupat udah dipotong, opor udah dibikin. Nastar udah di meja, kacang udah digaremin. Nggak afdhol kalo nggak Minal Aidin wal Faidzin, Taqabalallahu minnaa wa minkum.",
    "Lebaran tahun ini di perantauan, di perantauan rindu sendiri. Dengan segenap hati saya ucapkan, selamat hari raya Idul Fitri " + TAHUN_HIJRIAH + " H.",
    "Lupakan sejenak soal target perusahaan. Apalagi tekanan atasan. Sekarang saatnya kita maaf-maafan. Sambil santai nikmati liburan.",
    "Mawar mekar berseri di pagi hari, pancaran merah menyapa hati. Pesan dikirim sebagai utusan diri, mengucapkan selamat hari raya Idul Fitri " + TAHUN_HIJRIAH + " H.",
    "Mati lampu saat cari kain, karena gelap terpaksa pakai lilin. Minal aizin wal faidzin, mohon maaf lahir dan batin",
    "Meminum jamu untuk kesehatan, tuk cegah bersin hingga batuk. Meski kita saling berjauhan, pintu maafmu tetap kan ku ketuk.",
    "Mendengar bedug buka puasa, disambut semua dengan ceria. Perilaku yang lalu menjadi dosa, kembali suci di hari raya.",
    "Menjelang Lebaran, sebelum sinyal internet lambat. Sebelum kuota menipis. Aku mau mengucapkan Selamat Idul Fitri " + TAHUN_HIJRIAH + " H, minal aidzin wal faidzin mohon maaf lahir dan batin.",
    "Menulis buku tiap lembaran, berharap karya tak dilupakan. Selamat hari lebaran, khilaf dan lupa mohon dimaafkan.",
    "Meskipun bajuku tidak baru, aku kan datang dengan bangga. Rayakan lebaran penuh dengan haru, bermaafan dengan keluarga.",
    "Meski beberapa kata yang pernah membuat luka, semoga tidak membuat tali silaturahmi ini putus. Selamat Idul Fitri " + TAHUN_HIJRIAH + " H, mohon maaf lahir dan batin.",
    "Minum air sambil menyelam, berlagak pintar kayak pahlawan. Dari lubuk hati yang dalam, maafkanlah dosaku kawan.",
    "Orang sekampung merasa iba, karena THR tak bersisa. Satu syawal segera tiba, mohon maaf dari segala dosa.",
    "Pulau pandan jauh ke tengah, Gunung daik bercabang tiga. Makan sudah salaman pun sudah, THR janganlah dilupa.",
    "Reset khilaf atau restart hati? Asal jangan di-shut down. Sedikit error bisa diperbaiki, asal jangan hang. Mohon maaf lahir dan batin.",
    "Saat flu sering bersin, kepala berat badan meriang. Kalau aku sering ngeselin, maafin aku ya sayang.",
    "Saat lenganku tak bisa merangkulmu untuk lebih dekat dengan hatiku. Aku selalu memelukmu dengan doa-doaku. Semoga kedamaian Allah selalu bersamamu. Selamat Idul Fitri " + TAHUN_HIJRIAH + " H.",
    "Sebelum matahari terbit, biarkan aku menghiasai setiap sinarnya dengan harapan untuk kesuksesan, kemakmuran, dan kebahagiaan untukmu dan keluargamu. Selamat hari raya.",
    "Sebening fiber optic, setinggi tower antena radio, secepat broadband access. Saya beserta keluarga memohon dibukakan bandwidth maaf sebesar-besarnya.",
    "Sebulan penuh siang tak makan, patutlah jika turun timbangan. Tak usah ragu saling memaafkan, agar bersama meraih kemenangan.",
    "Selamat Merayakan Hari Raya Idul Fitri " + TAHUN_HIJRIAH + " H. Semoga di hari yang fitri ini kita mampu kembali ke jatidiri insani menjadi pribadi-pribadi yang kepada siapapun, kapanpun dan dimanapun mampu menebar damai dan saling berbagi.",
    "Selambat apa pun jaringan internetku sehingga chat jadi pending terus, tetapi saya mewakili seluruh keluarga tetap berusaha untuk mengucapkan selamat Idul Fitri " + TAHUN_HIJRIAH + " H, minal aidzin walfaizin, mohon maaf lahir dan batin.",
    "Sepatu baru ada, celana baru ada, pakaian baru ada, kopiah baru juga ada. Namun, yang belum kupunya yaitu maaf darimu. Selamat Idul Fitri " + TAHUN_HIJRIAH + " H, mohon maaf lahir dan bathin.",
    "Walau sesibuk apa pun operator dan pesanku pending terus menerus, saya mewakili seluruh keluarga tetap teguh untuk mengucapkan Selamat Hari Raya Idul Fitri " + TAHUN_HIJRIAH + " H, minal aidin wal faizin.",
    "Wangi kue Lebaran kucium di sana sini, kunikmati dan kumakan sesuka hati. Kadang malu juga sih, tapi inilah Idul Fitri " + TAHUN_HIJRIAH + " H. Segala berkah harus kita nikmati.",
    "Selamat Hari Raya Idul Fitri " + TAHUN_HIJRIAH + " H, semoga suasana lebaranmu secerah kebahagiaan di wajahmu saat kamu ngabuburit.",
    "Selamat hari raya Idul Fitri " + TAHUN_HIJRIAH + " H, semoga rizki berlimpah ruah tiada terkira. Kue lebaran dan ketupat sudah tersedia, Kue lebaran dan ketupat sudah tersedia.",
]

module.exports = kumpulanUcapan