name: my-lebaran-bot

on: 
  pull_request:
    branches:
      - master
      
  schedule:
    - cron: "0 4,16 * * *"
      
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
           
    - name: Deploy application
      uses: okteto/deploy-stack@master
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TAHUN_HIJRIAH: "1444"
      with:
        build: "true"
        namespace: lebaran-bot-thesuhu
