name: my-lebaran-bot

on:
  pull_request:
    branches:
      - master

  schedule:
    - cron: "0 4,16 * * *"

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login to Okteto
        uses: okteto/login@v1
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Deploy application
        uses: okteto/deploy-stack@v1
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TAHUN_HIJRIAH: "1444"
        with:
          build: "true"
          namespace: telegram-bot-thesuhu
