on:
  # push:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  run_pull:
    name: Run Pull
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH keys
        # check this thread to understand why its needed:
        # https://stackoverflow.com/a/70447517
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Check if SSH connection is successful
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "exit"
      - name: Check and create SSH_WORKDIR (if needed)
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "if [ ! -d ${{ secrets.SSH_WORKDIR }} ]; then mkdir -p ${{ secrets.SSH_WORKDIR }}; fi"
      - name: Check and clone repo (if needed)
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.SSH_WORKDIR }} && if [ ! -d ${{ env.REPO_NAME }} ]; then git clone git@github.com:thesuhu/${{ env.REPO_NAME }}.git; fi"
      - name: Check and create .env file (if needed)
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.SSH_WORKDIR }}/${{ env.REPO_NAME }} && test -f .env || touch .env"
      - name: Pull
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.SSH_WORKDIR }}/${{ env.REPO_NAME }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && exit"
      - name: Cleanup
        run: rm -rf ~/.ssh
